import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional
from config.settings import CONFIG
from core.picks import Pick

log = logging.getLogger(__name__)

AFFILIATE_URL = "https://t.me/ValueEdgeFreePicks"
PAID_TG_URL = "https://whop.com/value-edge-972e/valueedge-signals"
SUBSTACK_URL = "https://valueedge.substack.com"

_CSS = """
body{font-family:'Georgia',serif;background:#080808;color:#e8e8e8;margin:0;padding:0}
.wrapper{max-width:640px;margin:0 auto;padding:32px 16px}
.header{border-bottom:2px solid #00ff87;padding-bottom:16px;margin-bottom:32px}
.header h1{font-size:28px;color:#00ff87;margin:0 0 4px 0}
.header p{color:#888;font-size:14px;margin:0}
.section-title{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:#00ff87;margin:32px 0 16px 0}
.pick-card{background:#1a1a1a;border-left:3px solid #00ff87;border-radius:4px;padding:18px 20px;margin-bottom:16px}
.pick-card.ht{border-left-color:#ff8c00}
.pick-match{font-size:17px;font-weight:bold;color:#fff;margin:0 0 4px 0}
.pick-meta{font-size:13px;color:#aaa;margin:0 0 12px 0}
.pick-bet{font-size:15px;color:#00ff87;margin:0 0 12px 0}
.pick-bet.ht{color:#ff8c00}
.stats{display:flex;gap:16px;flex-wrap:wrap}
.stat{background:#111;border-radius:3px;padding:6px 10px;font-size:13px}
.stat span{color:#00ff87;font-weight:bold}
.set-prices{margin-top:12px;font-size:12px;color:#888;border-top:1px solid #222;padding-top:10px}
.cta-btn{display:inline-block;background:#00ff87;color:#000;font-weight:bold;padding:12px 24px;border-radius:4px;text-decoration:none;font-size:14px;margin:24px 0}
.disclaimer{font-size:11px;color:#444;margin-top:24px;line-height:1.6}
"""

def _pick_card(pick):
    ht_cls = " ht" if pick.ht_model else ""
    ht_label = "🔶 HT MODEL — " if pick.ht_model else ""
    stats = f"""
    <div class="stats">
      <div class="stat">Edge <span>{pick.edge_pct:.1f}pp</span></div>
      <div class="stat">Fair <span>{pick.fair_odds:.2f}</span></div>
      <div class="stat">Market <span>{pick.market_odds:.2f}</span></div>
      <div class="stat">Value <span>+{pick.value_pct:.1f}%</span></div>
      {"<div class='stat'>Strength <span>" + f"{pick.strength:.0f}/100</span></div>" if pick.strength else ""}
      {"<div class='stat'>n <span>" + f"{pick.n_matches}</span></div>" if pick.n_matches else ""}
    </div>"""
    set_html = ""
    if pick.fair_2_0 or pick.fair_2_1 or pick.fair_win_1set:
        parts = []
        if pick.fair_2_0: parts.append(f"2-0: <b>{pick.fair_2_0:.2f}</b>")
        if pick.fair_2_1: parts.append(f"2-1: <b>{pick.fair_2_1:.2f}</b>")
        if pick.fair_win_1set: parts.append(f"Win 1+ set: <b>{pick.fair_win_1set:.2f}</b>")
        set_html = f'<div class="set-prices">Set prices: {" | ".join(parts)}</div>'
    return f"""
    <div class="pick-card{ht_cls}">
      <p class="pick-match">{pick.emoji} {pick.match}</p>
      <p class="pick-meta">{pick.league} · {pick.kickoff_str}</p>
      <p class="pick-bet{ht_cls}">✅ {ht_label}{pick.market} → {pick.selection}</p>
      {stats}{set_html}
    </div>"""

def build_weekly_html(football_picks, tennis_picks, week_label=None):
    today = date.today()
    wlabel = week_label or f"Week of {today.strftime('%d %b %Y')}"
    fb_section = ""
    if football_picks:
        cards = "".join(_pick_card(p) for p in football_picks)
        fb_section = f'<p class="section-title">⚽ Football Value Bets</p>{cards}'
    tn_section = ""
    if tennis_picks:
        cards = "".join(_pick_card(p) for p in tennis_picks)
        tn_section = f'<p class="section-title">🎾 Tennis Value Bets</p>{cards}'
    total = len(football_picks) + len(tennis_picks)
    return f"""<!DOCTYPE html>
    <html><head><meta charset="UTF-8"><style>{_CSS}</style></head>
    <body><div class="wrapper">
      <div class="header">
        <h1>📊 ValueEdge Weekly</h1>
        <p>{wlabel} · {total} qualifying picks</p>
      </div>
      <p style="color:#ccc;font-size:15px;line-height:1.7">
        Picks generated by Poisson (football) and Markov-chain (tennis) models.
        Only bets above edge threshold published. All results tracked transparently.
      </p>
      {fb_section}{tn_section}
      <a href="{PAID_TG_URL}" class="cta-btn">Join paid Telegram for daily signals →</a>
      <div class="disclaimer">
        ⚠️ Model output only — not financial advice. Bet responsibly.
        <a href="#" style="color:#555">Unsubscribe</a>
      </div>
    </div></body></html>"""

def send_weekly_digest(football_picks, tennis_picks, recipients=None):
    cfg = CONFIG.substack
    to_list = recipients or [cfg.substack_email]
    if not to_list or not to_list[0]:
        log.error("No recipient email configured")
        return False
    if CONFIG.dry_run:
        log.info(f"[DRY RUN] Weekly digest → {to_list} | fb={len(football_picks)} tn={len(tennis_picks)}")
        return True
    subject = f"📊 ValueEdge Weekly — {date.today().strftime('%d %b %Y')}"
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = cfg.from_email
    msg["To"] = ", ".join(to_list)
    msg.attach(MIMEText(build_weekly_html(football_picks, tennis_picks), "html"))
    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(cfg.smtp_user, cfg.smtp_pass)
            server.sendmail(cfg.from_email, to_list, msg.as_string())
        log.info(f"✅ Weekly digest sent to {len(to_list)} recipient(s)")
        return True
    except Exception as e:
        log.error(f"Email error: {e}")
        return False
